<a target="_blank" href="https://colab.research.google.com/github/victorlymarev/pandas/blob/main/notebooks/03-create-tables.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Код из видео

Если вы будете работать с этим ноутбуком в google colab и у вас что-то не будет работать, то раскоментируйте ячейку ниже (для этого выделите содержимое ячейки и нажмите на клавиши ctrl / (если смотреть по английской раскладке или ctrl . для русской), либо просто руками уберите # и пробел после нее в каждой строчке) и запустите ее.

In [ ]:
# import os
# os._exit(00)
# !pip install pyarrow pandas==1.5.3

In [1]:
import pandas as pd
import numpy as np

## Создание объекта Series

### На основе одного значения

In [2]:
pd.Series(1)

0    1
dtype: int64

In [3]:
pd.Series('pandas')

0    pandas
dtype: object

### На основе списка

In [4]:
['Аня', 'Маша', 'Вася', 'Катя', 'Аня']

['Аня', 'Маша', 'Вася', 'Катя', 'Аня']

In [5]:
pd.Series(['Аня', 'Маша', 'Вася', 'Катя', 'Аня']).value_counts()

Аня     2
Маша    1
Вася    1
Катя    1
dtype: int64

## Создание датафреймов

### На основе словаря

In [6]:
people_dict = {
    'Имя': ['Екатерина', 'Евгений', 'Андрей', 'Виктория', 'Анастасия', 'Данил'],
    'Фамилия': [pd.NA, 'Бубликов', 'Васильев', 'Леонова', 'Долгова',
                'Новиков'],
    'Дата рождения': pd.to_datetime(['1992-06-25', '1995-09-09', '2000-02-29',
                                     '1999-06-15', '2003-04-06', '1995-06-03']),
    'Количество детей': 0,
    'Дата увольнения': pd.Timestamp('12-06-2023')
}

In [7]:
pd.DataFrame(people_dict)

Имя   Фамилия Дата рождения  Количество детей Дата увольнения
0  Екатерина      <NA>    1992-06-25                 0      2023-12-06
1    Евгений  Бубликов    1995-09-09                 0      2023-12-06
2     Андрей  Васильев    2000-02-29                 0      2023-12-06
3   Виктория   Леонова    1999-06-15                 0      2023-12-06
4  Анастасия   Долгова    2003-04-06                 0      2023-12-06
5      Данил   Новиков    1995-06-03                 0      2023-12-06

#### Проверка длинны объектов

In [8]:
len(['Екатерина', 'Евгений', 'Андрей', 'Виктория', 'Анастасия', 'Данил'])

6

#### Функция len у датафреймов считает количество строк

In [9]:
len(pd.DataFrame(people_dict))

6

#### shape

Возвращает кортеж, первое значение в кортеже - количество строк, а второе - количество столбцов

In [10]:
pd.DataFrame(people_dict).shape

(6, 5)

## Функции для создания периодических чисел или дат

### np.arange

Генерирует целые числа

#### Синтаксис

1. np.arange(первое число в массиве, последнее число в массиве невключительно, шаг (по умолчанию равен 1))
2. np.arange(последнее число в массиве невключительно)

In [11]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [12]:
np.arange(-100, 80, 1.5)

array([-100. ,  -98.5,  -97. ,  -95.5,  -94. ,  -92.5,  -91. ,  -89.5,
        -88. ,  -86.5,  -85. ,  -83.5,  -82. ,  -80.5,  -79. ,  -77.5,
        -76. ,  -74.5,  -73. ,  -71.5,  -70. ,  -68.5,  -67. ,  -65.5,
        -64. ,  -62.5,  -61. ,  -59.5,  -58. ,  -56.5,  -55. ,  -53.5,
        -52. ,  -50.5,  -49. ,  -47.5,  -46. ,  -44.5,  -43. ,  -41.5,
        -40. ,  -38.5,  -37. ,  -35.5,  -34. ,  -32.5,  -31. ,  -29.5,
        -28. ,  -26.5,  -25. ,  -23.5,  -22. ,  -20.5,  -19. ,  -17.5,
        -16. ,  -14.5,  -13. ,  -11.5,  -10. ,   -8.5,   -7. ,   -5.5,
         -4. ,   -2.5,   -1. ,    0.5,    2. ,    3.5,    5. ,    6.5,
          8. ,    9.5,   11. ,   12.5,   14. ,   15.5,   17. ,   18.5,
         20. ,   21.5,   23. ,   24.5,   26. ,   27.5,   29. ,   30.5,
         32. ,   33.5,   35. ,   36.5,   38. ,   39.5,   41. ,   42.5,
         44. ,   45.5,   47. ,   48.5,   50. ,   51.5,   53. ,   54.5,
         56. ,   57.5,   59. ,   60.5,   62. ,   63.5,   65. ,   66.5,
      

In [13]:
np.arange(100, 0, -1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

### np.linspace

Делит отрезок на равные части

#### Синтаксис:

np.linspace(нначало отрезка, конц отрезка, число точек на отрезке)

In [14]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.linspace(5, 6, 8)

array([5.        , 5.14285714, 5.28571429, 5.42857143, 5.57142857,
       5.71428571, 5.85714286, 6.        ])

### pd.date_range(start, end, periods, freq)

__start__ - начало периода генерации дат

__end__ - конец периода генерации дат

__periods__ - количество дат для генерации

__freq__ - период, с которым даты будут генерироваться

In [16]:
pd.date_range('2020-09-06', '2023-05-18', periods=15).normalize()

DatetimeIndex(['2020-09-06', '2020-11-15', '2021-01-24', '2021-04-04',
               '2021-06-14', '2021-08-23', '2021-11-01', '2022-01-11',
               '2022-03-22', '2022-05-31', '2022-08-09', '2022-10-19',
               '2022-12-28', '2023-03-08', '2023-05-18'],
              dtype='datetime64[ns]', freq=None)

In [17]:
pd.date_range('2020-09-06 15:00', '2023-05-18', freq='2d 6h')

DatetimeIndex(['2020-09-06 15:00:00', '2020-09-08 21:00:00',
               '2020-09-11 03:00:00', '2020-09-13 09:00:00',
               '2020-09-15 15:00:00', '2020-09-17 21:00:00',
               '2020-09-20 03:00:00', '2020-09-22 09:00:00',
               '2020-09-24 15:00:00', '2020-09-26 21:00:00',
               ...
               '2023-04-27 15:00:00', '2023-04-29 21:00:00',
               '2023-05-02 03:00:00', '2023-05-04 09:00:00',
               '2023-05-06 15:00:00', '2023-05-08 21:00:00',
               '2023-05-11 03:00:00', '2023-05-13 09:00:00',
               '2023-05-15 15:00:00', '2023-05-17 21:00:00'],
              dtype='datetime64[ns]', length=438, freq='54H')

In [18]:
pd.date_range('2020-08-06 15:00', '2023-05-18', freq='MS').shift(5, 'd')

DatetimeIndex(['2020-09-06 15:00:00', '2020-10-06 15:00:00',
               '2020-11-06 15:00:00', '2020-12-06 15:00:00',
               '2021-01-06 15:00:00', '2021-02-06 15:00:00',
               '2021-03-06 15:00:00', '2021-04-06 15:00:00',
               '2021-05-06 15:00:00', '2021-06-06 15:00:00',
               '2021-07-06 15:00:00', '2021-08-06 15:00:00',
               '2021-09-06 15:00:00', '2021-10-06 15:00:00',
               '2021-11-06 15:00:00', '2021-12-06 15:00:00',
               '2022-01-06 15:00:00', '2022-02-06 15:00:00',
               '2022-03-06 15:00:00', '2022-04-06 15:00:00',
               '2022-05-06 15:00:00', '2022-06-06 15:00:00',
               '2022-07-06 15:00:00', '2022-08-06 15:00:00',
               '2022-09-06 15:00:00', '2022-10-06 15:00:00',
               '2022-11-06 15:00:00', '2022-12-06 15:00:00',
               '2023-01-06 15:00:00', '2023-02-06 15:00:00',
               '2023-03-06 15:00:00', '2023-04-06 15:00:00',
               '2023-05-

In [19]:
(pd.date_range('2020-08-06 15:00', '2023-05-18', freq='Y')
    .shift(5, 'M')
    .shift(-2, 'h')
)

DatetimeIndex(['2021-05-31 13:00:00', '2022-05-31 13:00:00',
               '2023-05-31 13:00:00'],
              dtype='datetime64[ns]', freq=None)

In [20]:
pd.date_range('2020-08-06 15:00', '2023-05-18', freq='min')

DatetimeIndex(['2020-08-06 15:00:00', '2020-08-06 15:01:00',
               '2020-08-06 15:02:00', '2020-08-06 15:03:00',
               '2020-08-06 15:04:00', '2020-08-06 15:05:00',
               '2020-08-06 15:06:00', '2020-08-06 15:07:00',
               '2020-08-06 15:08:00', '2020-08-06 15:09:00',
               ...
               '2023-05-17 23:51:00', '2023-05-17 23:52:00',
               '2023-05-17 23:53:00', '2023-05-17 23:54:00',
               '2023-05-17 23:55:00', '2023-05-17 23:56:00',
               '2023-05-17 23:57:00', '2023-05-17 23:58:00',
               '2023-05-17 23:59:00', '2023-05-18 00:00:00'],
              dtype='datetime64[ns]', length=1460701, freq='T')

### Список всех сокращений (регистр их записи не важен)

| Сокращение   | Расшифровка                              | Сокращение   | Расшифровка                    |
|:-------------|:-----------------------------------------|:-------------|:-------------------------------|
| B            | Последний рабочий день в неделе          | QS           | Начало квартала                |
| C            | Пользовательский последний день в неделе | BQS          | Первый рабочий день квартала   |
| D            | День                                     | A, Y         | Конец года                     |
| W            | Неделя                                   | BA, BY       | Последний рабочий день в году  |
| M            | Конец месяца                             | AS, YS       | Начало года                    |
| SM           | 15 число месяца                          | BAS, BYS     | Первый рабочий день в году     |
| BM           | Последний рабочий день в месяце          | BH           | Рабочий час (от 9:00 до 17:00) |
| CBM          | Пользовательский конец месяца            | H            | Час                            |
| MS           | Первое число месяца                      | T, min       | Минута                         |
| SMS          | 1 и 15 число месяца                      | S            | Секунда                        |
| BMS          | Первый рабочий день месяца               | L, ms        | Миллисекунда                   |
| CBMS         | Пользовательский первый день месяца      | U, us        | Микросекунда                   |
| Q            | Конец квартала                           | N            | Наносекунда                    |
| BQ           | Последний рабочий день квартала          | nan          | nan                            |

In [29]:
pd.date_range('2020-09-06', '2023-05-18', periods=15).normalize()

DatetimeIndex(['2020-09-06', '2020-11-15', '2021-01-24', '2021-04-04',
               '2021-06-14', '2021-08-23', '2021-11-01', '2022-01-11',
               '2022-03-22', '2022-05-31', '2022-08-09', '2022-10-19',
               '2022-12-28', '2023-03-08', '2023-05-18'],
              dtype='datetime64[ns]', freq=None)

In [41]:
pd.date_range('2020-09-06 15:00', '2023-05-18', freq='4d 7h')

DatetimeIndex(['2020-09-06 15:00:00', '2020-09-10 22:00:00',
               '2020-09-15 05:00:00', '2020-09-19 12:00:00',
               '2020-09-23 19:00:00', '2020-09-28 02:00:00',
               '2020-10-02 09:00:00', '2020-10-06 16:00:00',
               '2020-10-10 23:00:00', '2020-10-15 06:00:00',
               ...
               '2023-04-08 19:00:00', '2023-04-13 02:00:00',
               '2023-04-17 09:00:00', '2023-04-21 16:00:00',
               '2023-04-25 23:00:00', '2023-04-30 06:00:00',
               '2023-05-04 13:00:00', '2023-05-08 20:00:00',
               '2023-05-13 03:00:00', '2023-05-17 10:00:00'],
              dtype='datetime64[ns]', length=230, freq='103H')

In [50]:
(pd.date_range('2020-08-06 15:00', periods=15, freq='MS')
    .shift(5, 'd')
    .shift(8, 'min')
)

DatetimeIndex(['2020-09-06 15:08:00', '2020-10-06 15:08:00',
               '2020-11-06 15:08:00', '2020-12-06 15:08:00',
               '2021-01-06 15:08:00', '2021-02-06 15:08:00',
               '2021-03-06 15:08:00', '2021-04-06 15:08:00',
               '2021-05-06 15:08:00', '2021-06-06 15:08:00',
               '2021-07-06 15:08:00', '2021-08-06 15:08:00',
               '2021-09-06 15:08:00', '2021-10-06 15:08:00',
               '2021-11-06 15:08:00'],
              dtype='datetime64[ns]', freq=None)

# Задания

#### Описание таблиц лежит [здесь](https://github.com/victorlymarev/pandas/tree/main/tables)

Некоторые таблицы занимают много памяти, поэтому каждые 5-10 заданий лучше перезапускайте ноутбук.

Если вы будете работать с этим ноутбуком в google colab и у вас что-то не будет работать, то раскоментируйте ячейку ниже (для этого выделите содержимое ячейки и нажмите на клавиши ctrl / (если смотреть по английской раскладке или ctrl . для русской), либо просто руками уберите # и пробел после нее в каждой строчке) и запустите ее.

In [ ]:
# import os
# os._exit(00)
# !pip install pyarrow pandas==1.5.3

### Задание 1
Создайте объект Series, в котором будут лежать последовательно имена Аня, Наташа, Таня, Оля, Настя

In [ ]:
import pandas as pd

# напишите свой код здесь

### Задание 2
Создавать объекты Series можно на основе словарей. В этом случае ключ пойдет в индекс, а значение в тело колонки.

In [1]:
import pandas as pd

height = {'Кирилл': 178, 'Андрей': 189, 'Тимур': 159, 'Ярослав': 190}
pd.Series(height)

Кирилл     178
Андрей     189
Тимур      159
Ярослав    190
dtype: int64

Создайте на основе словаря объект Series. В индексе словаря пусть лежат имена Никита, Артур, Паша, а в значениях колонки номера телефонов 123456, 654321, 123321. 

In [ ]:
# напишите свой код здесь

### Задание 3
Создайте таблицу, состоящую из двух колонок. В перовой колонке должны быть имена Саша, Маша, Лера, Руслан. Во второй колонке пусть лежат фамилии Сидоров, Петрова, Иванова, Уткин

In [ ]:
import pandas as pd

# напишите свой код здесь

### Задание 4

В таблице marks_6d лежат оценки школьников в классе 6Д. Какое количество школьников в классе?

In [ ]:
import os
import pandas as pd
path_marks_6d = '../tables/оценки 6Д.csv' if os.path.exists('../tables/оценки 6Д.csv') else 'https://drive.google.com/uc?id=1aMvwur2zrISbVPRo86qWgbHPEpw5km0n'
marks_6d = pd.read_csv(path_marks_6d)
marks_6d

In [ ]:
# напишите свой код здесь

### Задание 5

Создайте набор точек от 1 до 150 с интервалом 2

In [ ]:
import numpy as np

# напишите свой код здесь

### Задание 6

Создайте набор точек от 0 до 15 включительно с интервалом 1.5

In [ ]:
import numpy as np

# напишите свой код здесь

### Задание 7

На отрезке от 100 до 150 создайте 80 равноудаленных друг от друга точек

In [ ]:
import numpy as np

# напишите свой код здесь

### Задание 8

Создайте набор дат с 18 марта 1999 года до 28 февраля 2021 года с частотой в 1 день

In [ ]:
import pandas as pd

# напишите свой код здесь

### Задание 9

Создайте набор дат с даты вашего рождения и до сегодняшнего дня с частотой в 1 день. При помощи функции len посчитайте длинну массива

In [ ]:
import pandas as pd

# напишите свой код здесь

### Задание 10

Создайте набор дат с 18 марта 2009 года до 28 февраля 2021 года с частотой в 4 дня 19 часов

In [ ]:
import pandas as pd

# напишите свой код здесь

### Задание 11

Создайте набор дат с 18 марта 2009 года до 18 февраля 2021 года с частотой в 1 месяц

In [ ]:
import pandas as pd

# напишите свой код здесь

### Задание 12

Создайте 8 дат с частотой в 3 часа начиная от 9 часов утра 21 декабря 1999 года

In [ ]:
import pandas as pd

# напишите свой код здесь